blank_issues_enabled: false
contact_links:
  - name: 🤔 General Questions
    url: https://github.com/pkal42/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or discuss ideas that don't fit the templates above
  - name: 📚 Documentation
    url: https://github.com/pkal42/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: View development guide and setup instructions